#!/bin/bash

#
# Settings
#
display=eDP-1-1
frec=60
ratio=1.77
minres=1280x720


get_resols () {
	declare -A _arr

	_arr=()

	minw=$(echo $minres | cut -d'x' -f1)
	minh=$(echo $minres | cut -d'x' -f2)

	resols=$(xrandr | egrep -o [0-9]+x[0-9]+)

	ix=0
	for res in ${resols[@]}; do
		_ratio=$(echo "scale=2; $res" | awk '{print $1,"/",$2}' FS="x" | bc -l)
		_w=$(echo $res | cut -d'x' -f1)
		_h=$(echo $res | cut -d'x' -f2)

		if [[ $(echo $ratio | bc -l) == $(echo $_ratio | bc -l) ]] && [[ $_w -ge $minw ]] && [[ $_h -ge minh ]]; then
			_arr[$res]+=1
		fi
		
		((ix++))
	done

	for res in ${!_arr[@]}; do
		selected_resols=(${selected_resols[@]} $res)	
	done

	IFS=$'\n' selected_resols=($(sort -r <<<"${selected_resols[*]}"))
	unset IFS
}


reset () {
	DISPLAY=:0 xrandr --output $display --auto
}

setresol () {
	wxh=$1

	[[ $wxh == "default" ]] && { reset; return; }

	wh=$(echo $wxh | awk '{print $1,$2}' FS="x")
	params=$(cvt $wh $frec | grep ^Modeline | cut -d' ' -f3-)
	set -- $params

	xrandr --newmode "${wxh}_$frec.00" $@ 2>/dev/null
	xrandr --addmode $display ${wxh}_$frec.00 2>/dev/null
	xrandr --output $display --mode ${wxh}_$frec.00 2>/dev/null
}

# Select automaticaly some resolutions 
get_resols

echo -e "Select resolution \n"

select res in ${selected_resols[@]} default
do
	echo "Changing to $res"
	sleep 1
	setresol "$res"
done
